name: Build kernel (ksu)

on:
  push:
    branches: [ mysterious ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc bison flex libssl-dev \
            libelf-dev cpio \
            python3 rsync wget git zip \
            llvm lld

      - name: Cache Clang Toolchain
        id: cache-clang
        uses: actions/cache@v4
        with:
          path: zyc-clang-16
          key: clang-16.0.6-20250721-release

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: "2G"
          key: kernel-ccache-${{ runner.os }}

      - name: Run build script
        run: |
          chmod +x ./ci/build_ksu_ci.sh
          ./ci/build_ksu_ci.sh

      - name: Upload AnyKernel3 zip
        uses: actions/upload-artifact@v4
        with:
          name: ReSukiSU-mysterious
          path: anykernel/*.zip

      - name: Upload Build log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

